### PR TITLE
:bug: just counting dynamic head append while mounting phase

### LINKED ISSUE #642: insertBefore未重写异常
## What happens?

现有A、B、C三个应用，这三个应用共同引用了同一套UI组件（样式都是通过insertBefore插入的），当我在A、B两个应用来回切换时，因为卸载沙盒会触发副作用重建，所以patchCount会变为负数。这时候我的切换到C，因为patchCount不为0的原因，所以他不会重写insertBefore方法，导致我的样式插入到了appName为A或B应用的节点中，导致`loader.js:35 Uncaught (in promise) Error: [qiankun] Wrapper element for appNameB with instance appNameB_1591472711221 is not existed!`

## 最小可复现仓库

描述已经很清晰了，原因也找到了

## 复现步骤，错误日志以及相关配置

```js
loader.js:35 Uncaught (in promise) Error: [qiankun] Wrapper element for appNameB with instance appNameB_1591472711221 is not existed!
    at assertElementExist (loader.js:35)
    at eval (loader.js:108)
    at HTMLHeadElement.insertBefore (dynamicHeadAppend.js:227)
    at insertStyleElement (VM231290 addStyles.js:177)
    at createStyleElement (VM231290 addStyles.js:219)
    at addStyle (VM231290 addStyles.js:296)
    at addStylesToDom (VM231290 addStyles.js:139)
    at module.exports (VM231290 addStyles.js:90)
    at eval (VM231492 _transform_condition.js:16)
```

## 相关环境信息

- **qiankun 版本**： v2.0.12
- **浏览器版本**： 83.0.4103.97（正式版本） （64 位）
- **操作系统**：windows 10

### PR DESCRIPTION
**Pull request by kuitos**
resolve #642 
resolve #643

---
This change is [Reviewable](https://reviewable.io/reviews/umijs/qiankun/645)

### CODE REVIEW

File: src/sandbox/patchers/dynamicHeadAppend.ts [hunk 1]
```diff
@@ -351,11 +351,16 @@ export default function patch(
...
+    patchCount++;
+  }
 
   return function free() {
-    patchCount--;
+    if (mounting) {
+      patchCount--;
+    }
 
+    console.log('patchCount--', patchCount);
```
Comment (howel52) [inline src/sandbox/patchers/dynamicHeadAppend.ts:363]: console 要去掉么

Comment (kuitos) [reply src/sandbox/patchers/dynamicHeadAppend.ts]: done
