### PR TITLE
:sparkles: inject the asset publicPath before app bootstrap

### LINKED ISSUE #137: 使用 create-react-app 创建出来的子项目，如果有 code split，子项目的 js 加载路径出错
## What happens?

在示例中，点击 app2 的子路由，会出现加载 js 文件出错的提示

## Mini Showcase Repository(REQUIRED)

https://github.com/jkchao/qiankun-error

## How To Reproduce

app-root 是主应用，安装包，启动子项目与主项目后，点击 app2 -> app2 的子路由，出现报错

## Context

- **Platform**: macOS
- **Browser Version**:  chrome 78
- **Node Version**: 10.15

### PR DESCRIPTION
**Pull request by kuitos**
resolve #137

---
This change is [Reviewable](https://reviewable.io/reviews/umijs/qiankun/147)

### CODE REVIEW

File: src/hijackers/publicPath.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
+/**
+ * @author Kuitos
+ * @since 2019-11-12
+ */
+import { Freer } from '../interfaces';
+
+declare global {
+  interface Window {
+    __INJECTED_PUBLIC_PATH_BY_QIANKUN__?: string;
```
Comment (howel52) [inline src/hijackers/publicPath.ts]: 这几个要不要放同一地方 https://github.com/umijs/qiankun/blob/d3b912a1b595f6c45a5531e0a31fc45bf060a22d/src/index.ts#L15

Comment (kuitos) [reply src/hijackers/publicPath.ts]: 👌
